Repository mulesoft/docs-code-builder, pull requests merged in 2023-07, with the labels that each got.

#56 W-13600668: Seamless setup mule management
  modules/ROOT/assets/image-source-files/open-settings.graffle
  modules/ROOT/assets/images/open-settings.png
  modules/ROOT/pages/manage-mule-runtime.adoc
  modules/ROOT/pages/troubleshooting.adoc
Labels: AUG, beta

#73 W-13751140-Review-DataWeave-execution-preview-CP
  modules/ROOT/pages/dataweave-execution-preview.adoc
Labels: AUG, beta

#72 W-13749551-Update-package-a-Mule-app-CP
  modules/ROOT/pages/package-mule-application.adoc
Labels: AUG, beta

#78 W-13729475 setup desktop duke
  modules/ROOT/assets/image-source-files/acb-not-logged-in.graffle
  modules/ROOT/assets/image-source-files/anypoint-code-builder-view.graffle
  modules/ROOT/assets/image-source-files/close-working-directory.graffle
  modules/ROOT/assets/image-source-files/design-api-1.graffle
  modules/ROOT/assets/image-source-files/develop-integration-option-mat.graffle
  modules/ROOT/assets/image-source-files/implement-api-option-mat.graffle
  modules/ROOT/assets/image-source-files/new-folder-home-directory.graffle
  modules/ROOT/assets/image-source-files/show-welcome-button.graffle
  modules/ROOT/assets/image-source-files/welcome-mat-reference.graffle
  modules/ROOT/assets/images/acb-not-logged-in.png
  modules/ROOT/assets/images/anypoint-code-builder-view.png
  modules/ROOT/assets/images/close-working-directory.png
  modules/ROOT/assets/images/design-api-1.png
  modules/ROOT/assets/images/develop-integration-option-mat.png
  modules/ROOT/assets/images/implement-api-option-mat.png
  modules/ROOT/assets/images/new-folder-home-directory.png
  modules/ROOT/assets/images/show-welcome-button.png
  modules/ROOT/assets/images/welcome-mat-reference.png
  modules/ROOT/nav.adoc
  modules/ROOT/pages/accept-terms-and-conditions.adoc
  modules/ROOT/pages/add-request-response-details.adoc
  modules/ROOT/pages/configure-default-output-panel.adoc
  modules/ROOT/pages/create-basic-integration.adoc
  modules/ROOT/pages/create-config-files.adoc
  modules/ROOT/pages/create-synchronization-sfdc-api.adoc
  modules/ROOT/pages/customize-look-and-feel.adoc
  modules/ROOT/pages/debug-a-mule-application.adoc
  modules/ROOT/pages/deploy-a-mule-application-to-cloudhub.adoc
  modules/ROOT/pages/deploy-mule-application.adoc
  modules/ROOT/pages/design-an-api-specification.adoc
  modules/ROOT/pages/design-api-specification-from-scratch.adoc
  modules/ROOT/pages/develop-an-integration.adoc
  modules/ROOT/pages/filter-search-results.adoc
  modules/ROOT/pages/implement-a-graphql-api-specification.adoc
  modules/ROOT/pages/implement-a-graphql-api.adoc
  modules/ROOT/pages/implement-a-local-api-guide.adoc
  modules/ROOT/pages/implement-a-rest-oas-api-specification.adoc
  modules/ROOT/pages/implement-an-api-specification.adoc
  modules/ROOT/pages/implement-local-api-specification.adoc
  modules/ROOT/pages/import-api-specification-from-exchange.adoc
  modules/ROOT/pages/import-dataweave-library.adoc
  modules/ROOT/pages/load-acb-web-ide.adoc
  modules/ROOT/pages/local-api-specification-tutorial.adoc
  modules/ROOT/pages/log-in-anypoint-platform.adoc
  modules/ROOT/pages/manage-web-ide-instance.adoc
  modules/ROOT/pages/mock-data-using-dw-library.adoc
  modules/ROOT/pages/package-mule-application.adoc
  modules/ROOT/pages/publish-api-spec-to-exchange.adoc
  modules/ROOT/pages/send-feedback.adoc
  modules/ROOT/pages/setup.adoc
  modules/ROOT/pages/test-graphql-first-implementation.adoc
  modules/ROOT/pages/upload-a-project.adoc
  modules/ROOT/pages/use-the-command-palette.adoc
  modules/ROOT/pages/work-on-home-directory.adoc
Labels: AUG, beta

#58 W-11725381-Update-configure-permissions-CP
  modules/ROOT/assets/image-source-files/acb-developer-permission.graffle
  modules/ROOT/assets/image-source-files/access-management-select-access.graffle
  modules/ROOT/assets/image-source-files/access-manangement-select-access.graffle
  modules/ROOT/assets/image-source-files/add-permissions.graffle
  modules/ROOT/assets/image-source-files/blue-icon-add-access-management.graffle
  modules/ROOT/assets/image-source-files/create-team-window.graffle
  modules/ROOT/assets/image-source-files/select-access-management.graffle
  modules/ROOT/assets/image-source-files/select-usename-access-management.graffle
  modules/ROOT/assets/image-source-files/select-username-access-management.graffle
  modules/ROOT/assets/image-source-files/select-users-access-management.graffle
  modules/ROOT/assets/image-source-files/start-using-these-features.graffle
  modules/ROOT/assets/image-source-files/teams-create-teams.graffle
  modules/ROOT/assets/image-source-files/teams-permissions.graffle
  modules/ROOT/assets/image-source-files/try-new-features-button.graffle
  modules/ROOT/assets/images/.DS_Store
  modules/ROOT/assets/images/acb-developer-permission.png
  modules/ROOT/assets/images/access-management-select-access.png
  modules/ROOT/assets/images/access-manangement-select-access.png
  modules/ROOT/assets/images/add-permissions.png
  modules/ROOT/assets/images/blue-icon-add-access-management.png
  modules/ROOT/assets/images/create-team-window.png
  modules/ROOT/assets/images/select-access-management.png
  modules/ROOT/assets/images/select-usename-access-management.png
  modules/ROOT/assets/images/select-username-access-management.png
  modules/ROOT/assets/images/select-users-access-management.png
  modules/ROOT/assets/images/start-using-these-features.png
  modules/ROOT/assets/images/teams-create-teams.png
  modules/ROOT/assets/images/teams-permissions.png
  modules/ROOT/assets/images/try-new-features-button.png
  modules/ROOT/pages/configure-permissions.adoc
Labels: AUG, beta

#74 W-13760953 choice router cv
  modules/ROOT/pages/_partials/mule-components/4.4/component-choice.adoc
  modules/ROOT/pages/acb-component-choice.adoc
Labels: OCT, ga

#71 W-13739778 parallel for each cv
  modules/ROOT/pages/_partials/mule-components/4.4/component-choice.adoc
  modules/ROOT/pages/_partials/mule-components/4.4/component-page-TEMPLATE-acb.adoc
  modules/ROOT/pages/_partials/mule-components/4.4/component-parallel-for-each.adoc
  modules/ROOT/pages/_partials/mule-components/4.4/component-partials-TEMPLATE.adoc
  modules/ROOT/pages/acb-component-choice.adoc
  modules/ROOT/pages/acb-component-parallel-for-each.adoc
Labels: OCT, ga

#52 W-13572835 overview suggestions duke
  modules/ROOT/pages/index.adoc
Labels: AUG, beta

#94 W-13596481 overview tweaks duke
  modules/ROOT/pages/index.adoc
Labels: AUG, beta

#91 W-13796916 import project duke
  modules/ROOT/pages/_partials/acb-ide-logos.adoc
  modules/ROOT/pages/implement-a-local-api-guide.adoc
  modules/ROOT/pages/upload-a-project.adoc
Labels: AUG, beta

#96 W-13810159 Update work-with-code-snippets.adoc
  modules/ROOT/assets/image-source-files/acb-auto-complete-options.graffle
  modules/ROOT/assets/images/acb-auto-complete-options.png
  modules/ROOT/assets/images/acb-dw-libraries.png
  modules/ROOT/pages/_partials/acb-prereq-login.adoc
  modules/ROOT/pages/create-xml-snippets.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/work-with-code-snippets.adoc
Labels: AUG, beta

#97 W-13796916 loading error (browser extension)
  modules/ROOT/assets/image-source-files/acb-start-flow-subflow-ui.graffle
  modules/ROOT/assets/image-source-files/troubleshoot-loading-error.graffle
  modules/ROOT/assets/images/acb-start-flow-subflow-ui.png
  modules/ROOT/assets/images/troubleshoot-loading-error.png
  modules/ROOT/nav.adoc
  modules/ROOT/pages/troubleshoot-app-loading-errors.adoc
  modules/ROOT/pages/troubleshoot-mule-runtime-errors.adoc
  modules/ROOT/pages/troubleshooting.adoc
Labels: AUG, beta

#76 W-13764567 secure config props duke
  modules/ROOT/assets/image-source-files/acb-project-directory.graffle
  modules/ROOT/assets/image-source-files/acb-snippet-secure-config-prop.graffle
  modules/ROOT/assets/images/acb-project-directory.png
  modules/ROOT/assets/images/acb-snippet-secure-config-prop.png
  modules/ROOT/pages/int-create-secure-configs.adoc
Labels: DO NOT MERGE!, AUG, beta

#98 W-13834199 config prop examples duke
  modules/ROOT/nav.adoc
  modules/ROOT/pages/int-create-secure-configs.adoc
Labels: AUG, beta

#99 W-13834199-config-prop-take3-duke
  modules/ROOT/pages/int-create-secure-configs.adoc
Labels: AUG, beta

#85 W-13790309 Review "mock-data-using-dw-library.adoc"
  modules/ROOT/pages/mock-data-using-dw-library.adoc
Labels: AUG, beta

#93 W-13763497 Review "local-api-specification-tutorial.adoc"
  modules/ROOT/pages/local-api-specification-tutorial.adoc
Labels: AUG, beta

#79 W-13776337 Review "Implement GraphQL API" docs
  modules/ROOT/pages/configure-graphql-flow-responses.adoc
  modules/ROOT/pages/implement-a-graphql-api.adoc
  modules/ROOT/pages/test-graphql-first-implementation.adoc
Labels: AUG, beta

#103 W-13834199 config prop take5 duke
  modules/ROOT/pages/int-create-secure-configs.adoc
Labels: AUG, beta
