Repository mulesoft/docs-code-builder, pull requests merged in 2023-08, with the labels that each got.

#57 W-13670063-Review Design an API Specification tutorial - CP
  modules/ROOT/assets/image-source-files/acb-api-console.graffle
  modules/ROOT/assets/image-source-files/acb-api-project.graffle
  modules/ROOT/assets/image-source-files/api-console-button.graffle
  modules/ROOT/assets/image-source-files/commit-changes.graffle
  modules/ROOT/assets/image-source-files/push-changes.graffle
  modules/ROOT/assets/image-source-files/set-api-version.graffle
  modules/ROOT/assets/images/acb-api-console.png
  modules/ROOT/assets/images/acb-api-project.png
  modules/ROOT/assets/images/commit-changes.png
  modules/ROOT/assets/images/push-changes.png
  modules/ROOT/assets/images/set-api-version.png
  modules/ROOT/nav.adoc
  modules/ROOT/pages/add-request-response-details.adoc
  modules/ROOT/pages/design-api-specification-from-scratch.adoc
  modules/ROOT/pages/design-api-specification.adoc
  modules/ROOT/pages/develop-integration.adoc
  modules/ROOT/pages/implement-api-specification.adoc
  modules/ROOT/pages/publish-api-spec-to-exchange.adoc
  modules/ROOT/pages/synchronize-with-design-center.adoc
  modules/ROOT/pages/test-api-specification.adoc
Labels: AUG, beta

#109 W-13899064 Review and test Slack integration tutorials
  modules/ROOT/pages/add-condition-to-your-flow.adoc
  modules/ROOT/pages/configure-slack-integration.adoc
  modules/ROOT/pages/create-config-files-slack-sfdc.adoc
  modules/ROOT/pages/create-escalation-slack-api.adoc
  modules/ROOT/pages/create-synchronization-sfdc-api.adoc
  modules/ROOT/pages/extract-payload-information.adoc
  modules/ROOT/pages/implement-a-local-api-guide.adoc
Labels: DO NOT MERGE!

#110 W-13898025 config incorp feedback simone duke
  modules/ROOT/assets/image-source-files/deploy-to-cloudhub-icon-with-deploy-json.graffle
  modules/ROOT/assets/image-source-files/deploy-to-cloudhub-icon-with-detail.graffle
  modules/ROOT/assets/image-source-files/int-secure-config-algorithms.graffle
  modules/ROOT/assets/images/deploy-to-cloudhub-icon-with-deploy-json.png
  modules/ROOT/assets/images/deploy-to-cloudhub-icon-with-detail.png
  modules/ROOT/assets/images/int-secure-config-algorithms.png
  modules/ROOT/pages/int-create-secure-configs.adoc
Labels: AUG, beta

#112 W-13923255-add-include-duke
  modules/ROOT/pages/_partials/acb-api-design.adoc
Labels: AUG, beta

#69 W-13739560 review deploy a mule app cp
  modules/ROOT/pages/deploy-mule-application.adoc
  modules/ROOT/pages/troubleshooting.adoc
Labels: AUG, beta

#60 W-13702334-Update-Develop-an-Integration-CP
  modules/ROOT/assets/image-source-files/empty-canvas-state.graffle
  modules/ROOT/assets/image-source-files/file-preferences-user-snippets.graffle
  modules/ROOT/assets/images/.DS_Store
  modules/ROOT/assets/images/empty-canvas-state.png
  modules/ROOT/assets/images/file-preferences-user-snippets.png
  modules/ROOT/pages/connect-to-a-db.adoc
  modules/ROOT/pages/create-basic-integration.adoc
  modules/ROOT/pages/create-xml-snippets.adoc
  modules/ROOT/pages/develop-integration.adoc
  modules/ROOT/pages/use-dataweave-to-transform-data.adoc
Labels: AUG, beta

#62 W-13714391-Review-implement-API-specification-PC
  modules/ROOT/assets/image-source-files/outline-list-location.graffle
  modules/ROOT/assets/image-source-files/outline-list-select-flow.graffle
  modules/ROOT/assets/image-source-files/rest-api-asset-type.graffle
  modules/ROOT/assets/image-source-files/scafolded-mule-config-file.graffle
  modules/ROOT/assets/images/outline-list-select-flow.png
  modules/ROOT/assets/images/rest-api-asset-type.png
  modules/ROOT/assets/images/scafolded-mule-config-file.png
  modules/ROOT/nav.adoc
  modules/ROOT/pages/implement-api-interface-logic.adoc
  modules/ROOT/pages/implement-api-specification.adoc
  modules/ROOT/pages/import-api-specification-from-exchange.adoc
Labels: AUG, beta

#115 W-13923255-marketplace-link-duke
  modules/ROOT/pages/setup.adoc
Labels: AUG, beta

#66 W-13735979-Review-Debug-a-Mule-app-CP
  modules/ROOT/assets/image-source-files/debug-add-expression.graffle
  modules/ROOT/assets/image-source-files/debugger-stop-db-select.graffle
  modules/ROOT/assets/image-source-files/debugger-stop-set-variable.graffle
  modules/ROOT/assets/image-source-files/debugger-toolbar.graffle
  modules/ROOT/assets/image-source-files/debugger-view.graffle
  modules/ROOT/assets/image-source-files/packaged-and-running-terminals.graffle
  modules/ROOT/assets/image-source-files/tut-debug-mediatype-java.graffle
  modules/ROOT/assets/image-source-files/tut-debug-mediatype-json.graffle
  modules/ROOT/assets/images/acb-dw-run-preview.png
  modules/ROOT/assets/images/acb-my-integration-loading.png
  modules/ROOT/assets/images/debug-add-expression.png
  modules/ROOT/assets/images/debugger-stop-db-select.png
  modules/ROOT/assets/images/debugger-stop-set-variable.png
  modules/ROOT/assets/images/debugger-toolbar.png
  modules/ROOT/assets/images/debugger-view.png
  modules/ROOT/assets/images/packaged-and-running-terminals.png
  modules/ROOT/assets/images/tut-debug-mediatype-java.png
  modules/ROOT/assets/images/tut-debug-mediatype-json.png
  modules/ROOT/nav.adoc
  modules/ROOT/pages/debug-a-mule-application.adoc
  modules/ROOT/pages/debug-add-breakpoints.adoc
  modules/ROOT/pages/debug-add-logger-set-variables.adoc
  modules/ROOT/pages/implement-api-specification.adoc
  modules/ROOT/pages/ping-locally-deployed-app.adoc
  modules/ROOT/pages/run-a-debug-session.adoc
  modules/ROOT/pages/tut-debug-american-flights.adoc
Labels: AUG, beta

#106 W-13876942: Update local-api-specification-tutorial.adoc
  modules/ROOT/assets/image-source-files/select-deployment-environment.graffle
  modules/ROOT/assets/image-source-files/tut-api-create-project.graffle
  modules/ROOT/assets/image-source-files/tut-api-create.graffle
  modules/ROOT/assets/image-source-files/tut-api-multiroot-workspace.graffle
  modules/ROOT/assets/image-source-files/tut-api-publish.graffle
  modules/ROOT/assets/image-source-files/tut-api-publish.png
  modules/ROOT/assets/image-source-files/tut-api-stage-changes.graffle
  modules/ROOT/assets/image-source-files/tut-local-spec-implement.graffle
  modules/ROOT/assets/images/select-deployment-environment.png
  modules/ROOT/assets/images/tut-api-create-project.png
  modules/ROOT/assets/images/tut-api-create.png
  modules/ROOT/assets/images/tut-api-multiroot-workspace.png
  modules/ROOT/assets/images/tut-api-publish.png
  modules/ROOT/assets/images/tut-api-stage-changes.png
  modules/ROOT/assets/images/tut-local-spec-implement.png
  modules/ROOT/nav.adoc
  modules/ROOT/pages/implement-a-local-api-guide.adoc
  modules/ROOT/pages/local-api-specification-tutorial.adoc
Labels: AUG, beta

#134 W-14038638-tweak-title-duke debug-a-mule-application.adoc
  modules/ROOT/pages/debug-a-mule-application.adoc
Labels: beta

#142 W-14027494 link to KIs from troubleshooting.adoc
  modules/ROOT/pages/troubleshooting.adoc
  modules/ROOT/pages/upload-a-project.adoc
Labels: beta
